# Образ ОС с зависимостями для установки 1с

FROM debian:stretch-slim

ENV DEBIAN_FRONTEND noninteractive

# Установка локали
# && apt-get install -y apt-utils 

RUN apt-get update \
    && apt-get install -y locales \
    && localedef -i ru_RU -c -f UTF-8 -A /usr/share/locale/locale.alias ru_RU.UTF-8 \
    && `#----- Install the dependencies -----` \
    && apt-get install --yes --no-install-recommends fontconfig imagemagick procps \
    && apt-get install --yes --no-install-recommends libwebkitgtk-3.0-0  \   
    && rm -rf /var/lib/apt/lists/*  
    
ENV LANG ru_RU.utf8
ENV LC_ALL ru_RU.utf8
ENV LANGUAGE ru_RU.utf8

# Install 1C dependencies
# && `#----- Install the dependencies -----` 
# RUN apt-get install --yes --no-install-recommends fontconfig imagemagick procps \
#    && apt-get install --yes --no-install-recommends libwebkitgtk-3.0-0

CMD ["/bin/bash"]
